# Generated by Django 2.1 on 2018-08-26 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('peers', models.ManyToManyField(to='scraper.Instance')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('num_peers', models.IntegerField(blank=True, null=True)),
                ('num_statuses', models.IntegerField(blank=True, null=True)),
                ('num_users', models.IntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(max_length=100)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Instance')),
            ],
        ),
    ]
