# Generated by Django 2.1 on 2018-09-01 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('domain_count', models.IntegerField(blank=True, null=True)),
                ('status_count', models.IntegerField(blank=True, null=True)),
                ('user_count', models.IntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(max_length=100)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeerRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relationship', to='scraper.Instance')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relationships', to='scraper.Instance')),
            ],
        ),
        migrations.AddField(
            model_name='instance',
            name='peers',
            field=models.ManyToManyField(through='scraper.PeerRelationship', to='scraper.Instance'),
        ),
    ]
