# Generated by Django 2.1 on 2018-08-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='id',
        ),
        migrations.AlterField(
            model_name='instance',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instancestats',
            name='num_peers',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='instancestats',
            name='num_statuses',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='instancestats',
            name='num_users',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='instancestats',
            name='version',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
