# Generated by Django 2.1 on 2018-08-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
