# Generated by Django 2.1 on 2018-08-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20180826_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancestats',
            name='num_peers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instancestats',
            name='num_statuses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instancestats',
            name='num_users',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
