# Generated by Django 2.1 on 2018-08-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20180826_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instancestats',
            old_name='num_peers',
            new_name='domain_count',
        ),
        migrations.RenameField(
            model_name='instancestats',
            old_name='num_statuses',
            new_name='status_count',
        ),
        migrations.RenameField(
            model_name='instancestats',
            old_name='num_users',
            new_name='user_count',
        ),
        migrations.AddField(
            model_name='instance',
            name='user_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
