# Generated by Django 2.1 on 2018-08-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20180826_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='peers',
            field=models.ManyToManyField(to='scraper.Instance'),
        ),
    ]
